build:
  tags:
    - bcm
  script:
    - bash /etc/profile.d/modules.sh
    - module load cuda10.0/toolkit slurm
    - mkdir build
    - python3 graph_generator.py
    - cd build
    - cmake3 -DCODE_COVERAGE=ON -DENABLE_TESTING=ON ..
    - make -j5
    - srun -t 500 --gres=gpu:1 test_alg
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - bash <(curl -s https://codecov.io/bash) -f coverage.info -t $CODECOV
